/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codeminders_hidapi_HIDManager */

#ifndef _Included_com_codeminders_hidapi_HIDManager
#define _Included_com_codeminders_hidapi_HIDManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codeminders_hidapi_HIDManager
 * Method:    listDevices
 * Signature: ()[Lcom/codeminders/hidapi/HIDDeviceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_codeminders_hidapi_HIDManager_listDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
